apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
      - name: dockerapp
        image: ramkitcs/dockerapp:33
        ports:
        - containerPort: 80
